### ISSUE TITLE
unbound-checkconf: error while loading shared libraries: libunbound.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by doublefx** [MartineauUK/Unbound-Asuswrt-Merlin#13]
Hi,

I had a segmentation issue again, I followed [the procedure of last time it happened](https://github.com/MartineauUK/Unbound-Asuswrt-Merlin/issues/11#issuecomment-626241598)

but after that, this time, I'm getting:
_unbound-checkconf: error while loading shared libraries: libunbound.so.8: cannot open shared object file: No such file or directory_

What should I do?

**Comment by MartineauUK** [comment]
> Hi,
> 
> I had a segmentation issue again, I followed [the procedure of last time it happened](https://github.com/MartineauUK/Unbound-Asuswrt-Merlin/issues/11#issuecomment-626241598)
> 
> but after that, this time, I'm getting:
> _unbound-checkconf: error while loading shared libraries: libunbound.so.8: cannot open shared object file: No such file or directory_
> 
> What should I do?

As per the **unbound_manager Q&A/FAQ**

see http://www.snbforums.com/threads/release-unbound_manager-manager-installer-utility-for-unbound-recursive-dns-server.61669/post-548284

**NLNetLabs** have decided to to _revert_ their poor decision (back in April) to replace **'libunbound'** with **'libunbound-light'**

So you need to delete **'libunbound-light'** with **'libunbound'** 

`opkg remove libunbound-light --force-depends && opkg install libunbound`

**Comment by doublefx** [comment]
I did and for that:

![image](https://user-images.githubusercontent.com/1222171/93724302-cb737480-fb9d-11ea-88b3-005fb1e5b144.png)

Then tried Option 1 (Update unbound files...) and got:

/opt/var/lib/unbound/unbound.conf:142: error: cannot open include file '/opt/var/lib/unbound/adblock/adservers': No such file or directory
read /opt/var/lib/unbound/unbound.conf failed: 1 errors in configuration file

**Comment by MartineauUK** [comment]
Either uninstall **Adblock**, or I suggest you uninstall **unbound** then reinstall **unbound**.

**Comment by doublefx** [comment]
I felt like I had to do that too but preferred to ask you first, it fixed the issue, many thanks !
