### ISSUE TITLE
YouTube adblock not working from iOS app

### ISSUE THREAD

**Issue by zkkzkk32312** [MartineauUK/Unbound-Asuswrt-Merlin#19]
Hello,

I followed the instructions and suseesfully installed unbound through amtm and installed all the ad block options.
I have all the pre reqs checked with green and passing status.

Testing on an iPhone with YouTube app and it's not working at all.

Just wondering if this is to be expected?

**Comment by MartineauUK** [comment]
I didn't write/research the Youtube Adblocker, @Juched did.

It simply works by tracking the IP used for the advert, then adds it to a block list.

You can enquire on how many are in the current block list by using:

e.g.

`e  = Exit Script [?]

A:Option ==> ?

	Version=3.23b9					(Change Log: https://github.com/MartineauUK/Unbound-Asuswrt-Merlin/commits/dev/unbound_manager.sh)
	Local						md5=7a9d58be9c23dd663257445c84aa84a3
	Github						md5=6b4a500c071bcbb3f4a6e9596a178d43
	/jffs/addons/unbound/unbound_manager.md5	md5=6b4a500c071bcbb3f4a6e9596a178d43

	Router Configuration recommended pre-reqs status:

	[✔] Swapfile=1048572 kB
	[✔] DNS Filter=ON
	[✔] DNS Filter=ROUTER
	[✖] Warning WAN: Use local caching DNS server as system resolver=YES  		see http://10.88.8.1:80/Tools_OtherSettings.asp ->Advanced Tweaks and Hacks
	[✔] Entware NTP server 'S77chronyd' is running
	[✔] Enable DNS Rebind protection=NO
	[✔] Enable DNSSEC support=NO

	Options: Auto Reply='y' for User Selectable Options ('4') Performance Tweaks

	[✔] unbound CPU/Memory Performance tweaks
	[✔] Router Graphical GUI statistics TAB installed
	[✔] unbound-control FAST response ENABLED
	[✔] YouTube Ad Blocking (Forcing to use YT IP 62.24.208.79, No. of YouTube Video Ad domains=48)
<snip>
`

So in my example, 48 IP addresses are shown as being blocked, so if there are ONLY 100 IPs used to serve Youtube ads, then approx  50% of ads remain.

Sadly, there are probably thousands of IPs used, so it is very much a hit and miss solution, plus the fact that Google have probably devised detection methods to further reduce the effectiveness of the script.

**Comment by zkkzkk32312** [comment]
I see,

mine for some reason has even less Ad domains, no wonder its not really effective at all.

Version=3.22                                    (Change Log: https://github.com/MartineauUK/Unbound-Asuswrt-Merlin/commits/master/unbound_manager.sh)
        Local                                           md5=6b4a500c071bcbb3f4a6e9596a178d43
        Github                                          md5=6b4a500c071bcbb3f4a6e9596a178d43
        /jffs/addons/unbound/unbound_manager.md5        md5=6b4a500c071bcbb3f4a6e9596a178d43

        Router Configuration recommended pre-reqs status:

        [✔] Swapfile=2097148 kB
        [✔] DNS Filter=ON
        [✔] DNS Filter=ROUTER
        [✔] WAN: Use local caching DNS server as system resolver=NO
        [✔] Enable local NTP server=YES
        [✔] Enable DNS Rebind protection=NO
        [✔] Enable DNSSEC support=NO

        Options:

        [✔] Ad and Tracker Blocking (No. of Adblock domains=81230,Blocked Hosts=0,Allowlist=19,Blocked Country=2)
        [✔] Firefox DNS-over-HTTPS (DoH) DISABLE/Blocker
        [✔] Router Graphical GUI statistics TAB installed
        [✔] unbound-control FAST response ENABLED
        [✔] YouTube Ad Blocking (Forcing to use YT IP 209.91.104.14, No. of YouTube Video Ad domains=32)
