### ISSUE TITLE
Couple of typos - one breaking..

### ISSUE THREAD

**Issue by camkidd** [MartineauUK/Unbound-Asuswrt-Merlin#2]
https://github.com/MartineauUK/Unbound-Asuswrt-Merlin/blob/4c38426bd5273acba1b218e9a2dd73b951ac8980/unbound_manager.sh#L62

Hi, small typo that stops script finding unbound-control - should have ":" before the final $PATH.
ie: `export PATH=/sbin:/bin:/usr/sbin:/usr/bin:$PATH`

And also... 
https://github.com/MartineauUK/Unbound-Asuswrt-Merlin/blob/4c38426bd5273acba1b218e9a2dd73b951ac8980/unbound_manager.sh#L1202

Missing variable $. Think it should probably be `[ -n "$UPDATE_SCRIPT_ALERT" ]`

Thanks for your work on this.

**Comment by MartineauUK** [comment]
Thank you, in my haste I didn't review/add them.
