### ISSUE TITLE
Optiona 5, 6 and 7 out of screen

### ISSUE THREAD

**Issue by gjf** [MartineauUK/Unbound-Asuswrt-Merlin#22]
Options of menu 5-7 are out of screen due to limitaions of amtm menu width.

I really think the menu should not be displayed in columns to avoid this problem.

**Comment by MartineauUK** [comment]
![image](https://user-images.githubusercontent.com/27958379/164488819-6cecb919-96de-4a49-91ff-d58674e47f21.png)
