### ISSUE TITLE
can not update Entware package list

### ISSUE THREAD

**Issue by maxso-216** [MartineauUK/Unbound-Asuswrt-Merlin#24]
I think this error is specifics for older router. My router is RT-AC66U, which is out of supported by asus-merlin. 
Because of the old architecture the router is using (mipsel) , it uses old and discontinued  entware [repo](https://pkg.entware.net/binaries/mipsel/Packages.html), which does not ship `unbound-daemon`
So basically, it is impossible to use the manager.
I think it better to add some warning to users with older router.

**Comment by MartineauUK** [comment]
Entware is outside of  my control, so I don't keep track of package compatibility issues.

It could be that if you inform NL Labs, they may provide the necessary 'missing'  module, so if I were to add a warning/disclaimer now, it could be rendered obsolete in the future.

**Comment by maxso-216** [comment]
I have cross compiled necessary package for my router. So, is there a way to bypass the update warning?

------- Original Message -------
在 2023年4月13日 星期四 6:20 下午，MartineauUK ***@***.***> 寫道：
