### ISSUE TITLE
Unbound showing DNS Filter is off

### ISSUE THREAD

**Issue by novusB** [MartineauUK/Unbound-Asuswrt-Merlin#27]
I am running firmware version: 3004.388.7_1-gnuton1

I have an AX3000-V2. When I try to install unbound, the script tells me that I have DNS Filter off. From what I've researched, DNS Filter was changed to DNS Director. When I try to navigate to DNSFilter.asp I am greeted to a 404 error in my router. When I try to install unbound regardless, it errors out and doesn't install.

Any and all help is appreciated.

![unbound-dnserror](https://github.com/MartineauUK/Unbound-Asuswrt-Merlin/assets/155844237/0d116b29-727f-4ebb-bf9d-72c0a10c0979)

![unbound-dnserror2](https://github.com/MartineauUK/Unbound-Asuswrt-Merlin/assets/155844237/72b52755-9197-42ed-8eae-c400f5d02d65)

**Comment by Nullvoid3771** [comment]
Not a bug. Workaround as suggested on snb fourms for those interested. 

1: Go to https://routeraddress/DNSDirector.asp.
2: Enable DNS Director.
3: Set Global Redirection to "Router".
4: Install Unbound-Manager

**Comment by MartineauUK** [comment]
v3.24 Released
